select * where {
    ?s a ecrm:E22_Man-Made_Object;
        rdfs:label | dc:identifier ?label.

    ?production ecrm:P108_has_produced ?s;
        ecrm:P126_employed ?material ;
        ecrm:P4_has_time-span	/ rdfs:label	?time .
    OPTIONAL {?production ecrm:P8_took_place_on_or_within / rdfs:label ?location  }
    OPTIONAL {?production ecrm:P32_used_general_technique ?tech }

     ## FILTER BY MATERIAL ottoman
     # VALUES ?material {'ottoman'}

     ## FILTER BY TECHNIQUE doble tela
     VALUES ?tech {'doble tela'}

     ## FILTER BY TIME 15th  century
     # VALUES ?time {'15th  century'}

     ## FILTER BY LOCATION Italy
     # VALUES ?location {'Italy'}
}
