SELECT DISTINCT count(distinct ?prod) as ?count ?label
WHERE {
  VALUES ?g {
    <http://data.silknow.org/joconde>
    <http://data.silknow.org/garin>
    <http://data.silknow.org/imatex>
    <http://data.silknow.org/mad>
    <http://data.silknow.org/mtmad>
    <http://data.silknow.org/risd>
    <http://data.silknow.org/unipa>
  }


  GRAPH ?g {  ?prod a ecrm:E12_Production }
  ?prod  ecrm:P4_has_time-span ?ts
  {
    SELECT DISTINCT ?ts sql:BEST_LANGMATCH(?label, 'en, en-gb;q=0.8, *;q=0.1', '') as ?label
    WHERE { ?ts ecrm:P78_is_identified_by ?label }
  }
}
GROUP BY ?label
ORDER BY DESC(?count)
